# Generated by Django 3.2 on 2021-05-21 07:20

from django.db import migrations, models
import wishub.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wishub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(default=None, unique=True, validators=[wishub.utils.url_validator]),
        ),
    ]
