# Generated by Django 3.1.5 on 2021-05-20 22:46

from django.db import migrations, models
import django.db.models.deletion
import wishub.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wishub', '0002_auto_20210520_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wishub.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(default=None, validators=[wishub.utils.url_validator]),
        ),
    ]
